#!/bin/bash

#Run two 8 CPU splitting tasks per 16 CPU node.
#Note that the value of '8' within the parallel code cannot be parsed as a variable so if this 
#script is reconfigured to run on nodes with different numbers of CPUs, it will need to be 
#manually adjusted.  

#PBS -l wd
#PBS -P mo73 
#PBS -N split_fastq_oryx
#PBS -l walltime=8:00:00,mem=8Gb,ncpus=8,jobfs=4Gb
#PBS -W umask=022
#PBS -M jose.mijangosaraujo@sydney.edu.au
#PBS -m abe
#PBS -q normal

module load R/3.6.1
module load samtools/1.9

export R_LIBS=/home/549/jm9807/.R

Rscript split_fastq_oryx.R